variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}

variable "save_path" {
  type        = string
  default     = "."
  description = "Path to save the generated key-pair"
}
